### ISSUE TITLE
Hardcoded redirect IP in the AMI points to wrong address

### ISSUE THREAD

**Issue by mtekel** [concourse/concourse-lite#4]
In `/var/vcap/jobs/atc/bin/` scripts, there's `--external-url x.x.x.x` hardcoded. Probably that works in bosh lite, but in the AMI this points to wrong IP. The fix is to simply set `--external-url ''`, which does redirect back to whatever URL you have used to access the concourse. I think this should also work for bosh lite deployment....

**Comment by vito** [comment]
We're just gonna stop building the AWS box. It's really not a good idea to use it since there's no way to configure credentials. We've also never documented its existence (it just ends up being easy to find), and it's been broken for a while for other reasons.

I would recommend using [BOSH Lite](https://github.com/cloudfoundry/bosh-lite) instead.

**Comment by dcarley** [comment]
That's a shame. We've been using the AMI (0.70 with BasicAuth retro-fitted after boot) as way to "bootstrap" a more permanent Concourse instance, because we found that running `bosh-init` locally was too unreliable. I can understand the reasons for not wanting to maintain it for public consumption. I'm not sure that bosh-lite will be as simple though - it might be that we take the Packer configs and build our own.
